# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  PORT : 22
  HOST: 44.201.124.245
  USER: ubuntu
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: ng config -g cli.warnings.versionMismatch false
    - run: ng build 
    
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
       host: ${{env.HOST}}
       username: ${{env.USER}}
       port: ${{env.PORT}}
       key: ${{ secrets.SSHKEY }}
       source: "dist/proyecto-gps-frontend/*"
       target: "frontend"
 
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.1
      with:
       HOST: ${{env.HOST}}
       USER: ${{env.USER}}
       PRIVATE_SSH_KEY: ${{ secrets.SSHKEY }}
       COMMAND:  sudo rm -r /opt/lampp/htdocs/*.*; 
                 sudo mv frontend/dist/proyecto-gps-frontend/*.* /opt/lampp/htdocs/
                
       
       
